### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#230]
_Original author: domschuermann@gmail.com (April 09, 2012 21:36:54)_

from google play publisher console:

java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
at com.actionbarsherlock.internal.view.menu.MenuMule.clear(MenuMule.java:77)
at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:424)
at com.actionbarsherlock.app.SherlockFragmentActivity.onPreparePanel(SherlockFragmentActivity.java:263)
at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(ActionBarSherlock.java:564)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:491)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:269)
at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:968)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method)

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=229_

**Comment by 0-kaladin** [comment]
Upgrades to ActionBarSherlock resolved this.
