### ISSUE TITLE
Scan for Adware Crashes

### ISSUE THREAD

**Issue by Byyys** [Free-Software-for-Android/AdAway#617]
When i Start Adware scan... it crashes "unfortunately AdAway had stopped"

EDIT.. fixed AZ recorder was making it crash.

**Comment by mattjk** [comment]
I am having the same issue 

Device: Galaxy Note 4 N910F - Android Lollipop 5.0.1 (stock touchwiz bar root)

Start scanning = Unfortunately AdAway has stopped.

**Comment by 0-kaladin** [comment]
here is an output i gathered
```
05-14 23:57:50.732 E/JavaBinder(24911): !!! FAILED BINDER TRANSACTION !!!
05-14 23:57:50.733 E/AndroidRuntime(24911): FATAL EXCEPTION: ModernAsyncTask #2
05-14 23:57:50.733 E/AndroidRuntime(24911): Process: org.adaway, PID: 24911
05-14 23:57:50.733 E/AndroidRuntime(24911): java.lang.RuntimeException: An error occured while executing doInBackground()
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.lang.Thread.run(Thread.java:818)
05-14 23:57:50.733 E/AndroidRuntime(24911): Caused by: java.lang.RuntimeException: Package manager has died
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:111)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at org.adaway.util.ScanAdwareLoader.getAdPackages(ScanAdwareLoader.java:115)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at org.adaway.util.ScanAdwareLoader.loadInBackground(ScanAdwareLoader.java:58)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at org.adaway.util.ScanAdwareLoader.loadInBackground(ScanAdwareLoader.java:41)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	... 3 more
05-14 23:57:50.733 E/AndroidRuntime(24911): Caused by: android.os.TransactionTooLargeException
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.os.BinderProxy.transactNative(Native Method)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.os.BinderProxy.transact(Binder.java:496)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:1786)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:106)
05-14 23:57:50.733 E/AndroidRuntime(24911): 	... 11 more
05-14 23:57:50.738 W/ActivityManager(1342):   Force finishing activity 1 org.adaway/.ui.ScanAdwareActivity
```

**Comment by chesterx50** [comment]
Same on sm-g920v

**Comment by brainard52** [comment]
I believe I've got the same log as 0-kaladin. Here's the relevant information for my phone http://i.imgur.com/sLp5e4O.png

**Comment by starovdarkness** [comment]
Same here.... using Note 4 N910T.

**Comment by 0-kaladin** [comment]
http://developer.android.com/reference/android/os/TransactionTooLargeException.html

**Comment by 0-kaladin** [comment]
This is same issue facing #516 #626 and #633

**Comment by 0-kaladin** [comment]
This: https://github.com/Free-Software-for-Android/AdAway/commit/16e669edecbd4600f990cb9cf6771c555ea3e5bf
works around the issue for now, the scan for adware will at least no longer crash.
