### ISSUE TITLE
Copying of host files failed!

### ISSUE THREAD

**Issue by tux93** [Free-Software-for-Android/AdAway#745]
I'm having this Issue on CyanogenMod 13 with AdAway 3.1.1 and SuperSU 2.65

Logcat:
http://pastebin.com/raw/GJge5ZqU

**Comment by Dennis123789** [comment]
Core of the Logcat:

```
04-17 22:25:12.808  5743  6314 E AdAway  : Remounting as RW failed! Probably not a problem!
04-17 22:25:12.808  5743  6327 D RootCommands: Sending command(s): rm -f /system/etc/hosts 2>&1
04-17 22:25:12.808  5743  6394 D RootCommands: Closing shell
04-17 22:25:12.820  5743  6328 D RootCommands: ID: 1, Output: rm: can't remove '/system/etc/hosts': Read-only file system
04-17 22:25:12.820  5743  6328 D RootCommands: Command 1 finished.
04-17 22:25:12.821  5743  6314 D RootCommands: ID: 1, ExitCode: 1
04-17 22:25:12.821  5743  6327 D RootCommands: Sending command(s): dd if=/data/user/0/org.adaway/files/hosts of=/system/etc/hosts 2>&1
04-17 22:25:12.830  5743  6328 D RootCommands: ID: 2, Output: dd: can't open '/system/etc/hosts': Read-only file system
04-17 22:25:12.830  5743  6328 D RootCommands: Command 2 finished.
04-17 22:25:12.831  5743  6314 D RootCommands: ID: 2, ExitCode: 1
04-17 22:25:12.831  5743  6327 D RootCommands: Sending command(s): cat /data/user/0/org.adaway/files/hosts > /system/etc/hosts 2>&1
04-17 22:25:12.832  5743  6328 D RootCommands: Command 3 finished.
04-17 22:25:12.832  5743  6314 D RootCommands: ID: 3, ExitCode: 1
04-17 22:25:12.833  5743  6314 E AdAway  : Exception!
04-17 22:25:12.833  5743  6314 E AdAway  : org.adaway.util.CommandException
04-17 22:25:12.833  5743  6314 E AdAway  :      at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:176)
04-17 22:25:12.833  5743  6314 E AdAway  :      at org.adaway.service.ApplyService.apply(ApplyService.java:427)
04-17 22:25:12.833  5743  6314 E AdAway  :      at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:102)
04-17 22:25:12.833  5743  6314 E AdAway  :      at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
04-17 22:25:12.833  5743  6314 E AdAway  :      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
04-17 22:25:12.833  5743  6314 E AdAway  :      at android.os.Handler.dispatchMessage(Handler.java:102)
04-17 22:25:12.833  5743  6314 E AdAway  :      at android.os.Looper.loop(Looper.java:148)
04-17 22:25:12.833  5743  6314 E AdAway  :      at android.os.HandlerThread.run(HandlerThread.java:61)
04-17 22:25:12.833  5743  6314 I AdAway  : Remounting back to RO...
```

Looks like it's not able to delete or write to your hosts file. Have you tried changing the `Target hosts file` in preferences and applying again?

**Comment by tux93** [comment]
I did not and as I tried now It failed with `Symlink creation failed`, I have to see if I can create it manually in recovery.

This is not an HTC device btw.

**Comment by tux93** [comment]
Apparently updating to SuperSU Beta 2.71 fixed it
