### ISSUE TITLE
Adaway v3.1.1 crashes on upgrading database

### ISSUE THREAD

**Issue by Dennis123789** [Free-Software-for-Android/AdAway#746]
Says it's disabled with a red cross, when tapping it, it doesn't crash but logs:
```
04-18 10:59:43.194 org.adaway W/AdAway: Upgrading database from version 12 to 13
04-18 10:59:43.200 org.adaway E/AdAway: Private File can not be created, Exception: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: hosts_sources.url (code 2067)
```

When tapping the refresh icon in the toolbar, it crashes and logs:
```
04-18 11:00:47.464 org.adaway W/AdAway: Upgrading database from version 12 to 13
                                        
                                        --------- beginning of crash
04-18 11:00:47.478 org.adaway E/AndroidRuntime: FATAL EXCEPTION: IntentService[AdAwayUpdateService]
                                                Process: org.adaway, PID: 631
                                                Theme: themes:{default=overlay:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: hosts_sources.url (code 2067)
                                                    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                                                    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
                                                    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                    at org.adaway.provider.AdAwayDatabase.onUpgrade(AdAwayDatabase.java:213)
                                                    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                    at org.adaway.provider.AdAwayProvider.query(AdAwayProvider.java:179)
                                                    at android.content.ContentProvider.query(ContentProvider.java:1017)
                                                    at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
                                                    at android.content.ContentResolver.query(ContentResolver.java:493)
                                                    at android.content.ContentResolver.query(ContentResolver.java:435)
                                                    at org.adaway.provider.ProviderHelper.getEnabledHostsSourcesCursor(ProviderHelper.java:88)
                                                    at org.adaway.service.UpdateService.checkForUpdates(UpdateService.java:147)
                                                    at org.adaway.service.UpdateService.doWakefulWork(UpdateService.java:110)
                                                    at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:148)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Dennis123789** [comment]
I found the cause, it's because I already changed the URL from http to https manually a while ago.

The [onUpgrade](https://github.com/Free-Software-for-Android/AdAway/blob/9ce69a776b221503f563104f15de2a4ca7acc709/AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java#L208) method first deletes the http-variant, which is not present in my db. Than it inserts the https variant, which already is present, so it crashes because the url should be UNIQUE.

There's two solutions:

- Update the entry instead of deleting and inserting, this preserves the enabled setting too.
```
UPDATE hosts_sources
	SET url="https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
	WHERE url="http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext";
```

- Ignore when there's a duplicate key, by just suffixing `ON DUPLICATE KEY UPDATE id=id`
```
INSERT INTO hosts_sources (url, last_modified_local, last_modified_online, enabled)
	VALUES ("https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext", 0, 0, 1)
	ON DUPLICATE KEY UPDATE id=id;
```

This issue is present in every upgrade in onUpgrade. Which solution do you prefer? I'd prefer updating over ignoring.

**Comment by 0-kaladin** [comment]
Yes upgrading is preferred
